name: Needs context
 
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Build
        run: echo "Building the application..."
 
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: echo "Running tests after build..."
 
  deploy:
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        run: echo "Deploying the application after tests pass..."
